name: CI (Build & Test)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Show Java version
        run: java -version

      - name: Build and run tests
        run: mvn -B -q test

      - name: Package (skip tests)
        run: mvn -B -q -DskipTests package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: coda-demo-jar
          path: target/coda-demo-*.jar
          if-no-files-found: error

  dependency-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'coda-demo'
          path: '.'
          format: 'ALL'
          args: >-
            --enableRetired
            --failOnCVSS 0
            --noupdate

      - name: Upload Dependency-Check reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: |
            reports/dependency-check-report.html
            reports/dependency-check-report.json
          if-no-files-found: warn

  dependency-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Generate dependency update report
        run: |
          mvn -B -q versions:display-dependency-updates > dependency-updates.txt || true
          echo "Generated dependency-updates.txt"

      - name: Upload dependency updates report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-updates
          path: dependency-updates.txt
          if-no-files-found: error
